import { BookOpen, Activity, Users, Award, Flag, Sprout, Eye } from 'lucide-react'

export const COUNTRIES = [
  'Alemanha',
  'Angola',
  'Argentina',
  'Bolívia',
  'Brasil',
  'Cabo Verde',
  'Canadá',
  'Chile',
  'Colômbia',
  'Equador',
  'Espanha',
  'Estados Unidos',
  'França',
  'Itália',
  'Japão',
  'Moçambique',
  'México',
  'Paraguai',
  'Peru',
  'Portugal',
  'Reino Unido',
  'Uruguai',
  'Venezuela',
  'Outro',
]

export const BRAZILIAN_STATES = [
  'AC',
  'AL',
  'AP',
  'AM',
  'BA',
  'CE',
  'DF',
  'ES',
  'GO',
  'MA',
  'MT',
  'MS',
  'MG',
  'PA',
  'PB',
  'PR',
  'PE',
  'PI',
  'RJ',
  'RN',
  'RS',
  'RO',
  'RR',
  'SC',
  'SP',
  'SE',
  'TO',
]

export const LOCATIONS: Record<string, Record<string, string[]>> = {
  Brasil: {
    AC: ['Rio Branco', 'Cruzeiro do Sul', 'Sena Madureira'],
    AL: ['Maceió', 'Arapiraca', 'Rio Largo'],
    AP: ['Macapá', 'Santana', 'Laranjal do Jari'],
    AM: ['Manaus', 'Parintins', 'Itacoatiara'],
    BA: ['Salvador', 'Feira de Santana', 'Vitória da Conquista', 'Camaçari'],
    CE: ['Fortaleza', 'Caucaia', 'Juazeiro do Norte', 'Maracanaú'],
    DF: ['Brasília'],
    ES: ['Vitória', 'Vila Velha', 'Serra', 'Cariacica'],
    GO: ['Goiânia', 'Aparecida de Goiânia', 'Anápolis'],
    MA: ['São Luís', 'Imperatriz', 'São José de Ribamar'],
    MT: ['Cuiabá', 'Várzea Grande', 'Rondonópolis'],
    MS: ['Campo Grande', 'Dourados', 'Três Lagoas'],
    MG: ['Belo Horizonte', 'Uberlândia', 'Contagem', 'Juiz de Fora', 'Betim'],
    PA: ['Belém', 'Ananindeua', 'Santarém'],
    PB: ['João Pessoa', 'Campina Grande', 'Santa Rita'],
    PR: ['Curitiba', 'Londrina', 'Maringá', 'Foz do Iguaçu', 'Ponta Grossa'],
    PE: ['Recife', 'Jaboatão dos Guararapes', 'Olinda', 'Caruaru'],
    PI: ['Teresina', 'Parnaíba', 'Picos'],
    RJ: ['Rio de Janeiro', 'São Gonçalo', 'Duque de Caxias', 'Nova Iguaçu', 'Niterói'],
    RN: ['Natal', 'Mossoró', 'Parnamirim'],
    RS: ['Porto Alegre', 'Caxias do Sul', 'Pelotas', 'Canoas', 'Santa Maria'],
    RO: ['Porto Velho', 'Ji-Paraná', 'Ariquemes'],
    RR: ['Boa Vista', 'Rorainópolis'],
    SC: ['Florianópolis', 'Joinville', 'Blumenau', 'São José', 'Chapecó'],
    SP: [
      'São Paulo',
      'Guarulhos',
      'Campinas',
      'São Bernardo do Campo',
      'São José dos Campos',
      'Santo André',
      'Ribeirão Preto',
      'Osasco',
      'Sorocaba',
      'Mauá',
    ],
    SE: ['Aracaju', 'Nossa Senhora do Socorro', 'Lagarto'],
    TO: ['Palmas', 'Araguaína', 'Gurupi'],
  },
  Portugal: {
    Lisboa: ['Lisboa', 'Sintra', 'Cascais', 'Loures', 'Amadora'],
    Porto: ['Porto', 'Vila Nova de Gaia', 'Matosinhos', 'Gondomar'],
    Braga: ['Braga', 'Guimarães', 'Vila Nova de Famalicão'],
    Setúbal: ['Setúbal', 'Almada', 'Seixal'],
    Faro: ['Faro', 'Portimão', 'Loulé'],
    Coimbra: ['Coimbra', 'Figueira da Foz'],
    Aveiro: ['Aveiro', 'Ílhavo'],
    Madeira: ['Funchal', 'Câmara de Lobos'],
    Açores: ['Ponta Delgada', 'Angra do Heroísmo'],
  },
  Angola: {
    Luanda: ['Luanda', 'Viana', 'Cacuaco', 'Talatona', 'Belas'],
    Benguela: ['Benguela', 'Lobito', 'Baía Farta'],
    Huíla: ['Lubango', 'Matala'],
    Huambo: ['Huambo', 'Caála'],
    Cabinda: ['Cabinda'],
    Malanje: ['Malanje'],
  },
  Uruguai: {
    Montevideo: ['Montevideo'],
    Canelones: ['Ciudad de la Costa', 'Las Piedras', 'Barros Blancos'],
    Maldonado: ['Maldonado', 'Punta del Este', 'San Carlos'],
    Salto: ['Salto'],
    Paysandú: ['Paysandú'],
  },
  Outro: {
    Outro: ['Outra Cidade'],
  },
}

export const principles = [
  { title: 'Meritocracia', desc: 'Impacto real e comprovado.', icon: Award },
  { title: 'Valorização', desc: 'Foco na produção técnica.', icon: Award },
  { title: 'Liderança', desc: 'Atuação institucional.', icon: Flag },
  { title: 'Maturidade', desc: 'Progressão estruturada.', icon: Sprout },
  { title: 'Transparência', desc: 'Rastreabilidade total.', icon: Eye },
]

export const niveisData = [
  {
    id: 'I',
    title: 'Nível I - Observador Certificado',
    purpose: 'Construir autoridade técnica.',
    progress: 75,
    icon: BookOpen,
    items: [
      {
        title: 'Titulação Acadêmica',
        points: 200,
        desc: 'Comprovação de mestrado ou doutorado na área viária ou correlata.',
      },
      {
        title: 'Cursos Complementares',
        points: 50,
        desc: 'Certificados de cursos extracurriculares de especialização técnica.',
      },
      {
        title: 'Produção Técnica Publicada',
        points: 100,
        desc: 'Artigos, papers ou livros publicados e validados por pares.',
      },
    ],
  },
  {
    id: 'II',
    title: 'Nível II - Observador Certificado Pleno',
    purpose: 'Gerar transformação prática.',
    progress: 40,
    icon: Activity,
    items: [
      {
        title: 'Intervenções Técnicas',
        points: 150,
        desc: 'Projetos aplicados com impacto comprovado na redução de sinistros.',
      },
      {
        title: 'Produção Educativa',
        points: 80,
        desc: 'Desenvolvimento de materiais didáticos e metodologias para o trânsito.',
      },
      {
        title: 'Mobilização Social',
        points: 120,
        desc: 'Organização de eventos comunitários ou campanhas de conscientização locais.',
      },
    ],
  },
  {
    id: 'III',
    title: 'Nível III - Observador Certificado Mobilizador',
    purpose: 'Ocupação de espaços estratégicos e formação de novas lideranças.',
    progress: 15,
    icon: Users,
    items: [
      {
        title: 'Mentoria e Repasse',
        points: 200,
        desc: 'Atuação formal como mentor no programa. (Até 3x)',
      },
      {
        title: 'Representação em Comitês',
        points: 100,
        desc: 'Participação estratégica em comitês.',
      },
      {
        title: 'Campanhas (Maio Amarelo, JARI)',
        points: 50,
        desc: 'Atuação ativa em conselhos e câmaras técnicas.',
      },
    ],
  },
]
